name: cufs
description: A CLI tool to generate the Ultimate Flutter Stack.
version: 1.0.0
# publish_to: 'none' # Remove this line to publish to pub.dev
homepage: https://github.com/vivekvsingh19/create_ultimate_flutter_stack
repository: https://github.com/vivekvsingh19/create_ultimate_flutter_stack

topics:
  - cli
  - flutter
  - generator
  - template
  - productivity


environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  interact: ^2.1.1
  mason_logger: ^0.2.10
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
