name: cufs
description: A CLI tool to generate the Ultimate Flutter Stack.
version: 1.0.4

homepage: https://github.com/vivekvsingh19/create_ultimate_flutter_stack
repository: https://github.com/vivekvsingh19/create_ultimate_flutter_stack

topics:
  - cli
  - flutter
  - generator
  - template
  - productivity


environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  interact: ^2.1.1
  mason_logger: ^0.3.3
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0



executables:
  cufs:
